### ISSUE TITLE
World Age

### ISSUE THREAD

**Issue by MikaelSlevinsky** [JuliaGizmos/Interact.jl#161]
On version:
```julia
julia> versioninfo()
Julia Version 0.6.0-pre.alpha.220
Commit 89609cf* (2017-03-22 20:10 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin16.4.0)
  CPU: Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, haswell)
```
with master Interact and IJulia, I get a world age issue in IJulia:
```julia
using Interact
x = collect(linspace(-1,1,101))
f = sin.(10exp.(x));
@manipulate for i = 1:10
    i
end

5
KERNEL EXCEPTION
MethodError: no method matching (::##1#4)(::IJulia.Msg)
The applicable method may be too new: running in world age 21603, while current world is 21678.
Closest candidates are:
  #1(::Any) at /Users/Mikael/.julia/v0.6/Interact/src/IJulia/setup.jl:56 (method too new to be called from this world context.)

Stacktrace:
 [1] comm_msg(::ZMQ.Socket, ::IJulia.Msg) at /Users/Mikael/.julia/v0.6/IJulia/src/comm_manager.jl:135
 [2] eventloop(::ZMQ.Socket) at /Users/Mikael/.julia/v0.6/IJulia/src/eventloop.jl:8
 [3] (::IJulia.##9#12)() at ./task.jl:335

KERNEL EXCEPTION
MethodError: no method matching (::##1#4)(::IJulia.Msg)
The applicable method may be too new: running in world age 21603, while current world is 21678.
Closest candidates are:
  #1(::Any) at /Users/Mikael/.julia/v0.6/Interact/src/IJulia/setup.jl:56 (method too new to be called from this world context.)

Stacktrace:
 [1] comm_msg(::ZMQ.Socket, ::IJulia.Msg) at /Users/Mikael/.julia/v0.6/IJulia/src/comm_manager.jl:135
 [2] eventloop(::ZMQ.Socket) at /Users/Mikael/.julia/v0.6/IJulia/src/eventloop.jl:8
 [3] (::IJulia.##9#12)() at ./task.jl:335

KERNEL EXCEPTION
MethodError: no method matching (::##1#4)(::IJulia.Msg)
The applicable method may be too new: running in world age 21603, while current world is 21678.
Closest candidates are:
  #1(::Any) at /Users/Mikael/.julia/v0.6/Interact/src/IJulia/setup.jl:56 (method too new to be called from this world context.)

Stacktrace:
 [1] comm_msg(::ZMQ.Socket, ::IJulia.Msg) at /Users/Mikael/.julia/v0.6/IJulia/src/comm_manager.jl:135
 [2] eventloop(::ZMQ.Socket) at /Users/Mikael/.julia/v0.6/IJulia/src/eventloop.jl:8
 [3] (::IJulia.##9#12)() at ./task.jl:335
```

This is too cryptic for me to figure out; I'm not even sure if it's an Interact or IJulia issue.

**Comment by JobJob** [comment]
Hi, yeah a fix for this is coming soon, we're waiting on something in Base (more info here https://github.com/JuliaGizmos/Interact.jl/pull/158#issuecomment-281254446 if you're curious)

In the meantime I think you should be able to workaround this with the following changes:

Change [this line in IJulia](https://github.com/JuliaLang/IJulia.jl/blob/master/src/eventloop.jl#L8) to `eval(Expr(:call, handlers[msg.header["msg_type"]], socket, msg))`, and [this line in Reactive](https://github.com/JuliaGizmos/Reactive.jl/blob/master/src/core.jl#L162) to `isrequired(a) && eval(Expr(:call, a.f, a.recipient.value, timestep))`

Let me know how it goes.

**Comment by JobJob** [comment]
Actually looking at the error you might also have to change [this line](https://github.com/JuliaLang/IJulia.jl/blob/master/src/comm_manager.jl#L135) to 
```
eval(Expr(:call, comm.on_msg, msg))
```

**Comment by MikaelSlevinsky** [comment]
Thanks, the fix works! I only use Interact with plotting for demos, and it appears to have gotten a lot slower since July (on 0.4 then, 0.6 now). Any reason you can think of?

**Comment by JobJob** [comment]
Doing what exactly? moving sliders to update plots? Which plotting lib?

I've noticed the throttle on the number of updates for each move of the slider is working "better" as in the plot updates fewer times when you move the slider, but sometimes this makes things less smooth

**Comment by JobJob** [comment]
Glad it works btw :)

**Comment by timholy** [comment]
Probably fixed in https://github.com/JuliaLang/julia/pull/20820 (worth testing).

**Comment by timholy** [comment]
Or perhaps not. See https://github.com/JuliaLang/julia/issues/21141.

**Comment by SimonDanisch** [comment]
Yeah, still getting world age errors first time after precompilation.. but they seem to be gone after a restart... Still not tested very well from my side, though

**Comment by oschulz** [comment]
Any news on this? I just ran into this with Julia v0.6.0:

```
MethodError: no method matching (::##13#14{Interact.Options{:SelectionSlider,Float64}})(::IJulia.Msg)
The applicable method may be too new: running in world age [...]
```

**Comment by oschulz** [comment]
Restart didn't help, in my case.

**Comment by JobJob** [comment]
You might need to update IJulia

**Comment by JobJob** [comment]
Oh I think you need to `Pkg.checkout("IJulia")`, let me know how that goes. Prob need to get IJulia to tag a new release.

**Comment by JobJob** [comment]
@stevengj if you get a chance to tag an IJulia release that would be great! Interact doesn't work on julia 0.6 without the `invokelatest` changes.

**Comment by shashi** [comment]
I've tagged it. @JobJob @timholy many thanks to you fine folks for taking care of this <3

**Comment by dpsanders** [comment]
Can confirm that Interact works on the release of 0.6 with IJulia master (tag waiting to be merged: 
https://github.com/JuliaLang/METADATA.jl/pull/9891). Thanks to all!

**Comment by JobJob** [comment]
Cheers, have fun at juliacon everyone!

**Comment by oschulz** [comment]
Works for me too now - thanks a lot, @JobJob and @shashi!
