### ISSUE TITLE
Interact.jl not working in Jupyter Lab

### ISSUE THREAD

**Issue by vilim** [JuliaGizmos/Interact.jl#205]
With everything upgraded to the newest versions (Jupyter Lab 0.31.5, ipywidgets 7.1.1), the interactive widgets do not work in Jupyter Lab, however they work in Jupyter notebook, running from the same server (http://localhost:8888/tree)
The ipywidgets in python  in both the lab and classic notebook environments.
Also, the build command (Pkg.build("Interact")) fails with 
`LoadError: UndefVarError: @PYTHON_str not defined
while loading C:\Users\vilim\.julia\v0.6\Interact\deps\build.jl, in expression starting on line 3`

**Comment by stevengj** [comment]
The detection of the ipywidgets version is currently somewhat broken on Windows.  The `@PYTHON_str` error is because #200 forgot to use `\"` for a quotation mark in a string, cc @JobJob.

I'm working on a patch now.

**Comment by stevengj** [comment]
Should be fixed by #206.

**Comment by korsbo** [comment]
I have the same problem. However, I'm running linux, jupyterlab 0.31.8, ipywidgets 7.1.0 and I do not get any build errors. I still have this problem persists after #206.

**Comment by korsbo** [comment]
I just tried to use ipywidgets via python in jupyterlab. It failed. So my reported problem is not likely to be the fault of Interact.jl.

**Comment by shashi** [comment]
There's a very fundamental problem here that needs to be solved:

```
JupyterLab does not execute inline JavaScript in HTML output
```

**Comment by shashi** [comment]
I think one way to solve it is to write a Jupyter [server plugin](https://jupyter-notebook.readthedocs.io/en/stable/extending/handlers.html#writing-a-notebook-server-extension) which serves local `.js` files using Jupyter's server. I would like to bundle this plugin within Interact.jl, and somehow tell Jupyter to load it, but that may not be so easy.

We will need to start the `jupyter notebook` with the extension loaded, either with
```
jupyter notebook --NotebookApp.nbserver_extensions="{'mypackage.mymodule':True}"
```
or by editing a global config file at `~/.jupyter/jupyter_config.py`. I noticed that when I install `IJulia` from Conda.jl, I don't have this file...

A config file is also required to tell jupyter where to look for your server extension module -- you need to run `sys.path.append(...)` before asking jupyter to load the extension. So creating this config file is the only way this may work. I'm yet unsure how to reliably find / create / edit this config file...

(Related issue -- https://github.com/JuliaGizmos/WebIO.jl/issues/9)

**Comment by shashi** [comment]
```
    // TODO - arbitrary script execution is disabled for now.
    // Eval any script tags contained in the HTML. This is not done
    // automatically by the browser when script tags are created by
    // setting `innerHTML`. The santizer should have removed all of
    // the script tags for untrusted source, but this extra trusted
    // check is just extra insurance.
    // if (trusted) {
    //   // TODO do we really want to run scripts? Because if so, there
    //   // is really no difference between this and a JS mime renderer.
    //   Private.evalInnerHTMLScriptTags(host);
    // }
```
This clearly says they intend to support script tags in a "trusted" condition. I tried the "JS mime renderer", that doesn't work either.

![screenshot from 2018-02-22 20-21-24](https://user-images.githubusercontent.com/25916/36545087-19c23ebc-180e-11e8-9c42-7f06ed65717d.png)

**Comment by shashi** [comment]
The next step was to create an `unsafe-script` custom element and load it as a JS JypterLab extension. The full deal is here:

https://github.com/JuliaGizmos/WebIO.jl/pull/46

**Comment by oschulz** [comment]
Interactive elements seem to work for Python in JupyterLab (don't know since when):

https://blog.jupyter.org/jupyterlab-is-ready-for-users-5a6f039b8906

Does that only work because of the deep Integration between Python and Jupyter, or does it use some technique that we could access with Julia as well? Just wondering ... with JupyterLab rapidly maturing, it would be awesome to have Interact.jl working. :-)

**Comment by piever** [comment]
The latest (unreleased) version of Interact works on Jupyter lab, see [here](https://juliagizmos.github.io/Interact.jl/latest/deploying.html#Jupyter-notebook/lab-and-Juno-1) for setup instructions. Feel free to reopen the issue if those instructions do not work for you.
